import { TGood } from "../interfaces/types";

export const goods: TGood[] = [
  {
    artnumber: "0001",
    name: "Кастрюля",
    brand: "Tefal",
    weight: 1200,
    quantity: 1,
    price: 1700,
    stock: 1,
  },
  {
    artnumber: "0002",
    name: "Сковорода",
    brand: "КМЗ",
    weight: 1900,
    quantity: 1,
    price: 950,
    stock: 1,
  },
  {
    artnumber: "0003",
    name: "Ложка нерж.",
    brand: "Tescoma",
    weight: 95,
    quantity: 12,
    price: 1200,
    stock: 0,
  },
  {
    artnumber: "0004",
    name: "Спички",
    brand: "Красный коммунар",
    weight: 15,
    quantity: 20,
    price: 1,
    stock: 1,
  },
  {
    artnumber: "0005",
    name: "Сапоги",
    brand: "Timberland",
    weight: 5000,
    quantity: 1,
    price: 9000,
    stock: 1,
  },
  {
    artnumber: "0006",
    name: "Полуботинки",
    brand: "Timberland",
    weight: 3000,
    quantity: 1,
    price: 13000,
    stock: 1,
  },
  {
    artnumber: "0007",
    name: "Смартфон S8",
    brand: "Samsung",
    weight: 200,
    quantity: 1,
    price: 30000,
    stock: 1,
  },
  {
    artnumber: "0008",
    name: "Смартфон S9",
    brand: "Samsung",
    weight: 210,
    quantity: 1,
    price: 40000,
    stock: 1,
  },
  {
    artnumber: "0009",
    name: "Смартфон S10",
    brand: "Samsung",
    weight: 208,
    quantity: 1,
    price: 50000,
    stock: 0,
  },
  {
    artnumber: "0010",
    name: "Смартфон S20",
    brand: "Samsung",
    weight: 230,
    quantity: 1,
    price: 70000,
    stock: 1,
  },
  {
    artnumber: "0011",
    name: "Монитор",
    brand: "Samsung",
    weight: 4000,
    quantity: 1,
    price: 7000,
    stock: 1,
  },
  {
    artnumber: "0012",
    name: "Монитор",
    brand: "Samsung",
    weight: 5000,
    quantity: 1,
    price: 12000,
    stock: 0,
  },
  {
    artnumber: "0013",
    name: "Монитор",
    brand: "LG",
    weight: 4000,
    quantity: 1,
    price: 7000,
    stock: 1,
  },
  {
    artnumber: "0014",
    name: "Монитор",
    brand: "LG",
    weight: 5000,
    quantity: 1,
    price: 12000,
    stock: 0,
  },
];
